add `is_prerelease` param to GH releases
RevenueCat/purchases-ios pull request #1164
Opened 2022-01-11 19:06 UTC by aboedo

Currently, our beta GitHub releases aren't automatically marked as pre-release. 

We can do this automatically with fastlane, so I just added the param.

2022-01-11 19:07 UTC, aboedo commented on fastlane/Fastfile
> +
This isn't exactly fancy, but it does the job. 

A fancier alternative would be to use a [gem like sem-version](https://github.com/canton7/sem_version) to actually parse the version number, but it kinda feels like overkill right now. Happy to update if others feel it's important, though.

2022-01-11 21:39 UTC, joshdholtz requested changes
Just some small change to use `include?` otherwise this looks 💯

2022-01-11 21:39 UTC, joshdholtz commented on fastlane/Fastfile
> +    is_prerelease = new_version_number.split("-").length > 1
```suggestion
    is_prerelease = new_version_number.include?("-")
```

2022-01-12 14:15 UTC, aboedo commented on fastlane/Fastfile
> +    is_prerelease = new_version_number.split("-").length > 1
much cleaner, thanks!

2022-01-12 14:18 UTC, aboedo commented on fastlane/Fastfile
> +    is_prerelease = new_version_number.split("-").length > 1
updated!

2022-01-12 18:17 UTC, joshdholtz approved these changes
Beautiful! Ship it 💪 🚀

2022-01-12 18:28 UTC, merged

2022-01-12 18:52 UTC, beylmk commented
@aboedo can we make a follow-up ticket for the same in android?