Add Purchases.shared.setCleverTapID
RevenueCat/purchases-ios pull request #1269
Opened 2022-02-08 01:54 UTC by joshdholtz

### Checklist
- [x] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation
Fixes [sc-12973]
Noticed when making PurchaseTester for v4 testing tha `setCleverTapID` was missing and was forcing users to manually set `Purchases.shared.setAttributes(["$clevertapId" : clevertapId])`

### Description
Some quick copy/paste/edit from other integrations.

2022-02-08 02:17 UTC, NachoSoto reviewed
Reminder to add this to APITesters too :)

2022-02-08 02:20 UTC, joshdholtz commented
@NachoSoto I am never going to remember this 😛 Thank you for being the reminder that I need 😇

2022-02-08 16:09 UTC, aboedo commented
I wonder if we could automate that somehow. Maybe something [like this could help](https://github.com/apple/swift/blob/dd8b405dfbda027b8942e406ba67d95e98182b3e/tools/swift-api-digester/swift-api-digester.cpp), at least so that we can have an automatic PR comment saying "the public API has been modified, please update API testers"

2022-02-08 16:13 UTC, aboedo requested changes

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +    // region AirshipChannelID
I shouldn't be allowed to have simultaneously press command and C in a keyboard.

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +        self.subscriberAttributesManager.setAirshipChannelID(cleverTapID, appUserID: "kratos")
`setAirshipChannelID` -> `setCleverTapID`

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +        self.subscriberAttributesManager.setAirshipChannelID(cleverTapID, appUserID: "kratos")
`setAirshipChannelID` -> `setCleverTapID`

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +        self.mockDeviceCache.stubbedSubscriberAttributeResult = SubscriberAttribute(withKey: "$airshipChannelId",
`airshipChannelId` -> `cleverTapID`

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +        expect(receivedAttribute.key) == "$airshipChannelId"
`airshipChannelId` -> `cleverTapID`

2022-02-08 16:13 UTC, aboedo commented on PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
> +        expect(receivedAttribute.key) == "$airshipChannelId"
`airshipChannelId` -> `cleverTapID`

2022-02-09 15:24 UTC, aboedo approved these changes

2022-02-09 16:49 UTC, merged