Backend snapshot tests: separate snapshot for each major version
RevenueCat/purchases-ios pull request #1504
Opened 2022-04-13 20:06 UTC by NachoSoto

Fixes [CF-547].

This also removes the duplicate `BackendPostRecepitDataTests` for each version, as only 1 is needed now. `assertSnapshot` encodes the version in the filename.

2022-04-13 20:09 UTC, NachoSoto commented on Tests/UnitTests/TestHelpers/OSVersionEquivalent.swift
> +    }
This is the core of this PR. Thanks @taquitos for the idea.

2022-04-13 20:49 UTC, taquitos requested changes
Awesome stuff, one possible change I see some files prefixed like `iOSiOS15`

2022-04-13 20:49 UTC, taquitos commented on Tests/UnitTests/TestHelpers/OSVersionEquivalent.swift
> +extension OSVersionEquivalent {
🕺

2022-04-13 20:59 UTC, NachoSoto commented
Oops good catch! I forgot we have those separate tests as well.

2022-04-13 21:09 UTC, NachoSoto commented
Combined `BackendSubscriberAttributesTests` as well and updated snapshots.

2022-04-13 21:17 UTC, taquitos commented on Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
> +//  BackendPostReceiptDataTest.swift
`BackendPostReceiptDataTest` -> `BackendPostReceiptDataTests`

2022-04-13 21:18 UTC, taquitos approved these changes
The smallest comment update, but then 🚢

2022-04-13 21:19 UTC, NachoSoto commented on Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
> +//  BackendPostReceiptDataTest.swift
Oops thanks

2022-04-13 21:19 UTC, NachoSoto commented
I'll wait to merge this until somebody can generate the iOS 12 snapshots for me 🙏🏻

2022-04-13 21:29 UTC, taquitos commented
> I'll wait to merge this until somebody can generate the iOS 12 snapshots for me 🙏🏻

updating my Intel mac 🙃

2022-04-13 22:46 UTC, taquitos commented
@NachoSoto this is ready when you are 😄

2022-04-14 12:29 UTC, NachoSoto commented
Awesome thanks! Just pushed the comment fix, I'll merge this and make sure they're passing in `main`.

2022-04-14 12:31 UTC, merged