Prepare next version: 4.8.0-SNAPSHOT
RevenueCat/purchases-ios pull request #1750
Opened 2022-07-04 14:35 UTC by revenuecat-ops

2022-07-04 17:08 UTC, tonidero requested changes
Hmm I noticed an issue with my changes for fastlane... This is updating the version on the `plist` files to the version with `-SNAPSHOT`. The previous behavior changed those files to the version without modifiers... Working on a fix as I speak

2022-07-04 17:27 UTC, NachoSoto commented
Ooooh great catch! I missed that.

2022-07-04 17:55 UTC, NachoSoto approved these changes

2022-07-05 04:49 UTC, tonidero approved these changes

2022-07-05 04:50 UTC, merged