Fix path to storekit file in purchase tester
RevenueCat/purchases-ios pull request #2195
Opened 2022-12-29 16:54 UTC by mcastany

### Checklist
- [ ] If applicable, unit tests
- [ ] If applicable, create follow-up issues for `purchases-android` and hybrids

### Motivation
Fix issue on purchase tester

### Description

Fix path. When opening PurchaseTester and check the schema, I see this error

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1765468/209984410-a349d724-1b73-4642-b8db-405868ca3989.png">

2023-01-05 18:02 UTC, NachoSoto commented
Weird, this looks correct to me without the change. What version of Xcode are you using?

I tested your branch and it works too, so I'm not against it. I'm just confused 😅

2023-01-05 18:05 UTC, NachoSoto commented
I think the existing version is correct, I imagine the path should be relative to the project itself.
If you're on an older version of Xcode I wonder if they changed this, so maybe we should keep it as is since the current version is compatible with the latest Xcode 14.2?

2023-01-12 18:28 UTC, NachoSoto requested changes
Let me know if you agree with my assessment about Xcode 13 vs 14.

2023-01-17 13:36 UTC, aboedo commented
I get the path issue when using this branch and not in `main` ¯\_(ツ)_/¯

<img width="957" alt="Screenshot 2023-01-17 at 10 35 47 AM" src="https://user-images.githubusercontent.com/3922667/212912854-1411f524-6367-42fa-835d-fd7d8b242e14.png">

2023-01-17 13:55 UTC, aboedo commented
Just tried this again on a fresh clone just in case, same results. `Xcode 14.2 (14C18)`. 
@mcastany I'm closing this since I think the path was correct, but feel free to reopen if you think we should update

2023-01-17 13:55 UTC, closed without merging